version: v0.13.0

serve:
  public:
    base_url: https://{{ domain_name }}/auth/public/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: https://{{ domain_name }}/selfservice/welcome
  allowed_return_urls:
    - https://{{ domain_name }}/selfservice
    - http://localhost:19006/Callback
    - exp://localhost:8081/--/Callback

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: https://{{ domain_name }}/selfservice/error

    settings:
      ui_url: https://{{ domain_name }}/selfservice/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      ui_url: https://{{ domain_name }}/selfservice/recovery
      use: code

    verification:
      enabled: true
      ui_url: https://{{ domain_name }}/selfservice/verification
      use: code
      after:
        default_browser_return_url: https://{{ domain_name }}/selfservice/welcome

    logout:
      after:
        default_browser_return_url: https://{{ domain_name }}/selfservice/login
