name: containerize

on:
  workflow_dispatch:
    inputs:
      containerize_hydra:
        description: 'Containerize Hydra'
        required: false
        type: boolean
        default: false
      containerize_prometheus:
        description: 'Containerize Prometheus'
        required: false
        type: boolean
        default: false
      containerize_website:
        description: 'Containerize Website'
        required: false
        type: boolean
        default: false
      containerize_textlet_fe:
        description: 'Containerize Textlet Frontend'
        required: false
        type: boolean
        default: false
      containerize_textlet_be:
        description: 'Containerize Textlet Backend'
        required: false
        type: boolean
        default: false

jobs:
  containerize-hydra:
    if: ${{ inputs.containerize_hydra }}
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/hydra
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: build frontend assets with npm
        run: npm install && npm run build
      - name: log into Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build hydra container & push to GitHub registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hydra:latest

  containerize-prometheus:
    if: ${{ inputs.containerize_prometheus }}
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/prometheus
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: log into Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build prometheus container & push to GitHub registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/prometheus:latest

  containerize-website:
    if: ${{ inputs.containerize_website }}
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: arandombit/randomwebsite
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: log into Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build randomwebsite container & push to GitHub registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/randomwebsite:latest
