name: containerize

on:
  workflow_dispatch:

jobs:
  containerize-hydra:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: somenoodleshop/hydra
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: build frontend assets with npm
        run: npm install && npm run build
      - name: log into Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build hydra container & push to GitHub registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hydra:latest

  containerize-prometheus:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: somenoodleshop/prometheus
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: log into Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build prometheus container & push to GitHub registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/prometheus:latest

  containerize-website:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: somenoodleshop/randomwebsite
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: log into Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build randomwebsite container & push to GitHub registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/randomwebsite:latest
