name: destroy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: somenoodleshop/deploy
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
      - name: terraform init
        run: terraform init -backend-config="bucket=${{ secrets.BUCKET_NAME }}"
        env:
          TF_IN_AUTOMATION: true
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY_SECRET }}
