name: provision

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: somenoodleshop/deploy
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
      - name: terraform init
        run: terraform init -backend-config="bucket=${{ secrets.BUCKET_NAME }}"
        env:
          TF_IN_AUTOMATION: true
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY_SECRET }}
      - name: terraform apply
        id: terraform
        run: |
          terraform apply -auto-approve
          echo "IP: $(terraform output -raw droplet_ip_address)"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY_SECRET }}
          TF_VAR_digitalocean_ssh_key_name: ${{ secrets.DIGITALOCEAN_SSH_KEY_NAME }}
          TF_VAR_digitalocean_token: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TF_VAR_private_key: ${{ secrets.PRIVATE_KEY }}
          TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}
          TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
          TF_VAR_github_actor: ${{ github.actor }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: get droplet IP
        id: droplet_ip
        run: |
          echo "IP: $(terraform output -raw droplet_ip_address)"
          echo "ip=$(terraform output -raw droplet_ip_address)" >> $GITHUB_OUTPUT
      - name: install ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ steps.droplet_ip.outputs.ip }}"
          ssh-keyscan -H ${{ steps.droplet_ip.outputs.ip }} >> ~/.ssh/known_hosts
      - name: run ansible playbook
        run: ansible-playbook -i "${{ steps.droplet_ip.outputs.ip }}," playbook/main.yml --user root --private-key ${{ secrets.PRIVATE_KEY }}
